'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.1
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o vuelva a generar su proyecto de VS.
    '''<summary>
    '''  Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Señalizacion.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;no&quot; ?&gt;
        '''&lt;COLLADA xmlns=&quot;http://www.collada.org/2005/11/COLLADASchema&quot; version=&quot;1.4.1&quot;&gt;
        '''    &lt;asset&gt;
        '''        &lt;contributor&gt;
        '''            &lt;authoring_tool&gt;Google SketchUp 8.0.3117&lt;/authoring_tool&gt;
        '''        &lt;/contributor&gt;
        '''        &lt;created&gt;*FECHA_CREACION*&lt;/created&gt;
        '''        &lt;modified&gt;*FECHA_MODIFICACION*&lt;/modified&gt;
        '''        &lt;unit meter=&quot;0.02539999969303608&quot; name=&quot;inch&quot; /&gt;
        '''        &lt;up_axis&gt;Z_UP&lt;/up_axis&gt;
        '''    &lt;/asset&gt;
        '''    &lt;library_visual_scenes&gt;
        '''        &lt;visua [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property XML_SCHEME_CIRCULAR() As String
            Get
                Return ResourceManager.GetString("XML_SCHEME_CIRCULAR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;no&quot; ?&gt;
        '''&lt;COLLADA xmlns=&quot;http://www.collada.org/2005/11/COLLADASchema&quot; version=&quot;1.4.1&quot;&gt;
        '''    &lt;asset&gt;
        '''        &lt;contributor&gt;
        '''            &lt;authoring_tool&gt;Google SketchUp 8.0.3117&lt;/authoring_tool&gt;
        '''        &lt;/contributor&gt;
        '''        &lt;created&gt;*FECHA_CREACION*&lt;/created&gt;
        '''        &lt;modified&gt;*FECHA_MODIFICACION*&lt;/modified&gt;
        '''        &lt;unit meter=&quot;0.02539999969303608&quot; name=&quot;inch&quot; /&gt;
        '''        &lt;up_axis&gt;Z_UP&lt;/up_axis&gt;
        '''    &lt;/asset&gt;
        '''    &lt;library_visual_scenes&gt;
        '''        &lt;visua [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property XML_SCHEME_FAROLA() As String
            Get
                Return ResourceManager.GetString("XML_SCHEME_FAROLA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;no&quot; ?&gt;
        '''&lt;COLLADA xmlns=&quot;http://www.collada.org/2005/11/COLLADASchema&quot; version=&quot;1.4.1&quot;&gt;
        '''    &lt;asset&gt;
        '''        &lt;contributor&gt;
        '''            &lt;authoring_tool&gt;Google SketchUp 8.0.3117&lt;/authoring_tool&gt;
        '''        &lt;/contributor&gt;
        '''        &lt;created&gt;*FECHA_CREACION*&lt;/created&gt;
        '''        &lt;modified&gt;*FECHA_MODIFICACION*&lt;/modified&gt;
        '''        &lt;unit meter=&quot;0.02539999969303608&quot; name=&quot;inch&quot; /&gt;
        '''        &lt;up_axis&gt;Z_UP&lt;/up_axis&gt;
        '''    &lt;/asset&gt;
        '''    &lt;library_visual_scenes&gt;
        '''        &lt;visua [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property XML_SCHEME_OCTOGONAL() As String
            Get
                Return ResourceManager.GetString("XML_SCHEME_OCTOGONAL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;no&quot; ?&gt;
        '''&lt;COLLADA xmlns=&quot;http://www.collada.org/2005/11/COLLADASchema&quot; version=&quot;1.4.1&quot;&gt;
        '''    &lt;asset&gt;
        '''        &lt;contributor&gt;
        '''            &lt;authoring_tool&gt;Google SketchUp 8.0.3117&lt;/authoring_tool&gt;
        '''        &lt;/contributor&gt;
        '''        &lt;created&gt;*FECHA_CREACION*&lt;/created&gt;
        '''        &lt;modified&gt;*FECHA_MODIFICACION*&lt;/modified&gt;
        '''        &lt;unit meter=&quot;0.02539999969303608&quot; name=&quot;inch&quot; /&gt;
        '''        &lt;up_axis&gt;Z_UP&lt;/up_axis&gt;
        '''    &lt;/asset&gt;
        '''    &lt;library_visual_scenes&gt;
        '''        &lt;visua [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property XML_SCHEME_POSTE() As String
            Get
                Return ResourceManager.GetString("XML_SCHEME_POSTE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;no&quot; ?&gt;
        '''&lt;COLLADA xmlns=&quot;http://www.collada.org/2005/11/COLLADASchema&quot; version=&quot;1.4.1&quot;&gt;
        '''    &lt;asset&gt;
        '''        &lt;contributor&gt;
        '''            &lt;authoring_tool&gt;Google SketchUp 8.0.3117&lt;/authoring_tool&gt;
        '''        &lt;/contributor&gt;
        '''        &lt;created&gt;*FECHA_CREACION*&lt;/created&gt;
        '''        &lt;modified&gt;*FECHA_MODIFICACION*&lt;/modified&gt;
        '''        &lt;unit meter=&quot;0.02539999969303608&quot; name=&quot;inch&quot; /&gt;
        '''        &lt;up_axis&gt;Z_UP&lt;/up_axis&gt;
        '''    &lt;/asset&gt;
        '''    &lt;library_visual_scenes&gt;
        '''        &lt;visua [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property XML_SCHEME_RECTANGULAR() As String
            Get
                Return ResourceManager.GetString("XML_SCHEME_RECTANGULAR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;no&quot; ?&gt;
        '''&lt;COLLADA xmlns=&quot;http://www.collada.org/2005/11/COLLADASchema&quot; version=&quot;1.4.1&quot;&gt;
        '''    &lt;asset&gt;
        '''        &lt;contributor&gt;
        '''            &lt;authoring_tool&gt;Google SketchUp 8.0.3117&lt;/authoring_tool&gt;
        '''        &lt;/contributor&gt;
        '''        &lt;created&gt;*FECHA_CREACION*&lt;/created&gt;
        '''        &lt;modified&gt;*FECHA_MODIFICACION*&lt;/modified&gt;
        '''        &lt;unit meter=&quot;0.02539999969303608&quot; name=&quot;inch&quot; /&gt;
        '''        &lt;up_axis&gt;Z_UP&lt;/up_axis&gt;
        '''    &lt;/asset&gt;
        '''    &lt;library_visual_scenes&gt;
        '''        &lt;visua [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property XML_SCHEME_ROMBOIDAL() As String
            Get
                Return ResourceManager.GetString("XML_SCHEME_ROMBOIDAL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;no&quot; ?&gt;
        '''&lt;COLLADA xmlns=&quot;http://www.collada.org/2005/11/COLLADASchema&quot; version=&quot;1.4.1&quot;&gt;
        '''    &lt;asset&gt;
        '''        &lt;contributor&gt;
        '''            &lt;authoring_tool&gt;Google SketchUp 8.0.3117&lt;/authoring_tool&gt;
        '''        &lt;/contributor&gt;
        '''        &lt;created&gt;*FECHA_CREACION*&lt;/created&gt;
        '''        &lt;modified&gt;*FECHA_MODIFICACION*&lt;/modified&gt;
        '''        &lt;unit meter=&quot;0.02539999969303608&quot; name=&quot;inch&quot; /&gt;
        '''        &lt;up_axis&gt;Z_UP&lt;/up_axis&gt;
        '''    &lt;/asset&gt;
        '''    &lt;library_visual_scenes&gt;
        '''        &lt;visua [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property XML_SCHEME_TRAVESAÑO() As String
            Get
                Return ResourceManager.GetString("XML_SCHEME_TRAVESAÑO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;no&quot; ?&gt;
        '''&lt;COLLADA xmlns=&quot;http://www.collada.org/2005/11/COLLADASchema&quot; version=&quot;1.4.1&quot;&gt;
        '''    &lt;asset&gt;
        '''        &lt;contributor&gt;
        '''            &lt;authoring_tool&gt;Google SketchUp 8.0.3117&lt;/authoring_tool&gt;
        '''        &lt;/contributor&gt;
        '''        &lt;created&gt;*FECHA_CREACION*&lt;/created&gt;
        '''        &lt;modified&gt;*FECHA_MODIFICACION*&lt;/modified&gt;
        '''        &lt;unit meter=&quot;0.02539999969303608&quot; name=&quot;inch&quot; /&gt;
        '''        &lt;up_axis&gt;Z_UP&lt;/up_axis&gt;
        '''    &lt;/asset&gt;
        '''    &lt;library_visual_scenes&gt;
        '''        &lt;visua [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property XML_SCHEME_TRIANGULAR() As String
            Get
                Return ResourceManager.GetString("XML_SCHEME_TRIANGULAR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;no&quot; ?&gt;
        '''&lt;COLLADA xmlns=&quot;http://www.collada.org/2005/11/COLLADASchema&quot; version=&quot;1.4.1&quot;&gt;
        '''    &lt;asset&gt;
        '''        &lt;contributor&gt;
        '''            &lt;authoring_tool&gt;Google SketchUp 8.0.3117&lt;/authoring_tool&gt;
        '''        &lt;/contributor&gt;
        '''        &lt;created&gt;*FECHA_CREACION*&lt;/created&gt;
        '''        &lt;modified&gt;*FECHA_MODIFICACION*&lt;/modified&gt;
        '''        &lt;unit meter=&quot;0.02539999969303608&quot; name=&quot;inch&quot; /&gt;
        '''        &lt;up_axis&gt;Z_UP&lt;/up_axis&gt;
        '''    &lt;/asset&gt;
        '''    &lt;library_visual_scenes&gt;
        '''        &lt;visua [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property XML_SCHEME_TRIANGULAR_INVERTIDA() As String
            Get
                Return ResourceManager.GetString("XML_SCHEME_TRIANGULAR_INVERTIDA", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
